build.gradle, src/main/resources/application.properties
=> [#6]Setting: connect DB

src/main/java/com/spoonsors/spoonsorsserver/entity/BMember.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Delivery.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Fridge.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Ingredients.java, src/main/java/com/spoonsors/spoonsorsserver/entity/MealPlanner.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Post.java, src/main/java/com/spoonsors/spoonsorsserver/entity/SMember.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Spon.java
=> [#4]fix: erd 변경에 따른 entity 수정

build.gradle, src/main/java/com/spoonsors/spoonsorsserver/SpoonsorsserverApplication.java, src/main/java/com/spoonsors/spoonsorsserver/controller/bMember/FridgeController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Fridge.java, src/main/java/com/spoonsors/spoonsorsserver/entity/bMember/GetFridgeDto.java, src/main/java/com/spoonsors/spoonsorsserver/repository/FridgeRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/bMember/FridgeService.java, src/main/resources/application.properties
=> [#13]Feat: 냉장고 read api생성

src/main/java/com/spoonsors/spoonsorsserver/SpoonsorsserverApplication.java, src/main/java/com/spoonsors/spoonsorsserver/controller/manager/ManagerController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Ingredients.java, src/main/java/com/spoonsors/spoonsorsserver/repository/manager/ManagerRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/manager/ManagerService.java
=> [#17 #18]Feat: 관리자 Create Read API 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/bMember/FridgeController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Fridge.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Ingredients.java, src/main/java/com/spoonsors/spoonsorsserver/entity/bMember/FridgeDto.java, src/main/java/com/spoonsors/spoonsorsserver/repository/BMemberRepository.java, src/main/java/com/spoonsors/spoonsorsserver/repository/FridgeRepository.java, src/main/java/com/spoonsors/spoonsorsserver/repository/IFridgeRepository.java, src/main/java/com/spoonsors/spoonsorsserver/repository/IbMemberRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/bMember/FridgeService.java
=> [#12 #14]Feat: 냉장고 C/D API 생성

build.gradle, src/main/java/com/spoonsors/spoonsorsserver/entity/Fridge.java, src/main/resources/application.properties
resolved: #18 resolved: #19 resolved: #20
=> [#18 #19 #20]Feat: 관리자 식재료 R/U/D API 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/bMember/FridgeController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Delivery.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Fridge.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Ingredients.java, src/main/java/com/spoonsors/spoonsorsserver/entity/bMember/FridgeDto.java, src/main/java/com/spoonsors/spoonsorsserver/service/ImageUtils.java, src/main/java/com/spoonsors/spoonsorsserver/service/bMember/FridgeService.java
=> [#29]Fix: 냉장고 사진 저장/출력 수정

src/main/java/com/spoonsors/spoonsorsserver/controller/bMember/PostController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Ingredients.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Post.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Spon.java, src/main/java/com/spoonsors/spoonsorsserver/entity/bMember/PostDto.java, src/main/java/com/spoonsors/spoonsorsserver/repository/IPostRepository.java, src/main/java/com/spoonsors/spoonsorsserver/repository/ISponRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/bMember/PostService.java, src/main/java/com/spoonsors/spoonsorsserver/service/spon/SponService.java
=> [#33]Feat: 후원 글 등록 및 조회 API 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/manager/ManagerController.java, src/main/java/com/spoonsors/spoonsorsserver/controller/openApi/ApiController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Delivery.java, src/main/java/com/spoonsors/spoonsorsserver/entity/api/ApiDto.java, src/main/java/com/spoonsors/spoonsorsserver/service/openApi/ApiService.java
=> [#38 #39]Feat: 메뉴 전체 조회API, 이름으로 메뉴 조회 API 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/bMember/PostController.java, src/main/java/com/spoonsors/spoonsorsserver/repository/IPostRepository.java, src/main/java/com/spoonsors/spoonsorsserver/repository/PostRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/bMember/PostService.java
=> [#34]Feat: 내가 작성한 글 목록R API

src/main/java/com/spoonsors/spoonsorsserver/controller/bMember/PostController.java, src/main/java/com/spoonsors/spoonsorsserver/controller/mealPlanner/MealPlannerController.java, src/main/java/com/spoonsors/spoonsorsserver/controller/openApi/ApiController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Ingredients.java, src/main/java/com/spoonsors/spoonsorsserver/entity/MealPlanner.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Menu.java, src/main/java/com/spoonsors/spoonsorsserver/entity/api/ApiDto.java, src/main/java/com/spoonsors/spoonsorsserver/repository/IPostRepository.java, src/main/java/com/spoonsors/spoonsorsserver/repository/MealPlannerRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/bMember/PostService.java, src/main/java/com/spoonsors/spoonsorsserver/service/mealPlanner/MealPlannerService.java, src/main/java/com/spoonsors/spoonsorsserver/service/openApi/ApiService.java
=> [#41]Feat: 식단 C / R / U / D API 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/spon/SponController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/SMember.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Spon.java, src/main/java/com/spoonsors/spoonsorsserver/entity/spon/SponDto.java, src/main/java/com/spoonsors/spoonsorsserver/repository/ISMemberRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/spon/SponService.java
=> [#35]Feat: 후원 신청 및 내역 C / R API 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/review/ReviewController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Review.java, src/main/java/com/spoonsors/spoonsorsserver/entity/review/ReviewDto.java, src/main/java/com/spoonsors/spoonsorsserver/repository/IReviewRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/review/ReviewService.java
=> [#54]Feat: 리뷰 작성 API 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/bMember/PostController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Post.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Review.java, src/main/java/com/spoonsors/spoonsorsserver/entity/bMember/ViewPostDto.java, src/main/java/com/spoonsors/spoonsorsserver/entity/bMember/WritePostDto.java, src/main/java/com/spoonsors/spoonsorsserver/service/bMember/PostService.java
=> [#53]Fix: 후원글, 리뷰 매칭 위한 테이블 수정  및 포스트작성 API 수정

src/main/java/com/spoonsors/spoonsorsserver/controller/review/ReviewController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Review.java, src/main/java/com/spoonsors/spoonsorsserver/repository/ReviewRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/review/ReviewService.java
=> [#54 #55]Feat: 리뷰작성, 내가 작성한 리뷰 조회 API 생성

build.gradle, src/main/java/com/spoonsors/spoonsorsserver/SpoonsorsserverApplication.java, src/main/java/com/spoonsors/spoonsorsserver/controller/bMember/BMemberController.java, src/main/java/com/spoonsors/spoonsorsserver/controller/sMember/SMemberController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/BMember.java, src/main/java/com/spoonsors/spoonsorsserver/entity/BaseTime.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Role.java, src/main/java/com/spoonsors/spoonsorsserver/entity/SMember.java, src/main/java/com/spoonsors/spoonsorsserver/entity/bMember/BMemberSignUpDto.java, src/main/java/com/spoonsors/spoonsorsserver/entity/sMember/SMemberSignUpDto.java, src/main/java/com/spoonsors/spoonsorsserver/repository/ISMemberRepository.java, src/main/java/com/spoonsors/spoonsorsserver/repository/IbMemberRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/bMember/BMemberService.java, src/main/java/com/spoonsors/spoonsorsserver/service/sMember/SMemberService.java, src/main/resources/application.properties
=> [#60]Feat: 회원가입 API 생성

build.gradle, src/main/java/com/spoonsors/spoonsorsserver/controller/authorize/SmsController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/authorize/MessageDto.java, src/main/java/com/spoonsors/spoonsorsserver/entity/authorize/SmsRequestDto.java, src/main/java/com/spoonsors/spoonsorsserver/entity/authorize/SmsResponseDto.java, src/main/java/com/spoonsors/spoonsorsserver/service/authorize/SmsService.java, src/main/resources/application.properties
=> [#69]Feat: 휴대폰 본인인증 API 생성

src/main/java/com/spoonsors/spoonsorsserver/service/notificatin/FCMService.java, src/main/resources/firebase_service_key.json
=> [#82]Fix: fcm - 플러터 링크 추가

src/main/java/com/spoonsors/spoonsorsserver/controller/authorize/SmsController.java, src/main/java/com/spoonsors/spoonsorsserver/service/authorize/SmsService.java
=> [#69]Feat: 문자인증 요청, 확인 API 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/member/JoinController.java, src/main/java/com/spoonsors/spoonsorsserver/repository/BMemberRepository.java, src/main/java/com/spoonsors/spoonsorsserver/repository/SMemberRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/member/JoinService.java
=> [#86]Feat:아이디 찾기 API 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/member/JoinController.java, src/main/java/com/spoonsors/spoonsorsserver/repository/BMemberRepository.java, src/main/java/com/spoonsors/spoonsorsserver/repository/SMemberRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/member/BMemberService.java, src/main/java/com/spoonsors/spoonsorsserver/service/member/JoinService.java
=> [#90]Feat: 비밀번호 변경 API 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/payment/KakaoPayController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/payment/RequestPayDto.java, src/main/java/com/spoonsors/spoonsorsserver/service/payment/KakaoPayService.java
=> [#71]Fix: 카카오페이 openAPI 연결 수정

src/main/java/com/spoonsors/spoonsorsserver/controller/payment/KakaoPayController.java, src/main/java/com/spoonsors/spoonsorsserver/controller/spon/SponController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/payment/ApproveRequestPayDto.java, src/main/java/com/spoonsors/spoonsorsserver/entity/payment/Order.java, src/main/java/com/spoonsors/spoonsorsserver/service/payment/KakaoPayService.java, src/main/java/com/spoonsors/spoonsorsserver/service/spon/SponService.java
=> [#94]Fix: 후원 신청, 결제 api 통합

src/main/java/com/spoonsors/spoonsorsserver/controller/manager/ManagerController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/BMember.java, src/main/java/com/spoonsors/spoonsorsserver/entity/bMember/BMemberSignUpDto.java, src/main/java/com/spoonsors/spoonsorsserver/entity/manager/CertificateDto.java, src/main/java/com/spoonsors/spoonsorsserver/repository/BMemberRepository.java, src/main/java/com/spoonsors/spoonsorsserver/repository/ManagerRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/manager/ManagerService.java
=> [#96][#97]Feat: 수혜자 증명서 등록 상태 확인, 변경 API 생성

build.gradle, src/main/java/com/spoonsors/spoonsorsserver/ImageInfra/S3Config.java, src/main/java/com/spoonsors/spoonsorsserver/controller/manager/ManagerController.java, src/main/java/com/spoonsors/spoonsorsserver/controller/member/FridgeController.java, src/main/java/com/spoonsors/spoonsorsserver/controller/review/ReviewController.java, src/main/java/com/spoonsors/spoonsorsserver/controller/spon/SponController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/BMember.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Fridge.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Ingredients.java, src/main/java/com/spoonsors/spoonsorsserver/entity/Review.java, src/main/java/com/spoonsors/spoonsorsserver/entity/SMember.java, src/main/java/com/spoonsors/spoonsorsserver/entity/bMember/BMemberSignUpDto.java, src/main/java/com/spoonsors/spoonsorsserver/entity/bMember/GetFridgeDto.java, src/main/java/com/spoonsors/spoonsorsserver/entity/manager/CertificateDto.java, src/main/java/com/spoonsors/spoonsorsserver/entity/manager/GetManagerDto.java, src/main/java/com/spoonsors/spoonsorsserver/entity/sMember/SMemberSignUpDto.java, src/main/java/com/spoonsors/spoonsorsserver/entity/spon/SponDto.java, src/main/java/com/spoonsors/spoonsorsserver/service/Image/S3Uploader.java, src/main/java/com/spoonsors/spoonsorsserver/service/manager/ManagerService.java, src/main/java/com/spoonsors/spoonsorsserver/service/member/FridgeService.java, src/main/java/com/spoonsors/spoonsorsserver/service/review/ReviewService.java, src/main/resources/application.properties
=> [#101]Fix: 이미지 저장 aws S3로 변경

src/main/java/com/spoonsors/spoonsorsserver/controller/openApi/ApiController.java, src/main/java/com/spoonsors/spoonsorsserver/service/openApi/ApiService.java
=> [#103]Feat: 밥, 반찬, 국&찌개 분류 별 검색 API 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/member/PostController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/BMember.java, src/main/java/com/spoonsors/spoonsorsserver/repository/PostRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/member/PostService.java
resolved: #112, resolved: #113
=> [#112][#113]Feat: 후원글 작성 가능 상태 변경, 후원글 자체 삭제 API 생성

src/main/java/com/spoonsors/spoonsorsserver/service/review/ReviewService.java
=> [#112]Fix: 리뷰 작성 시 후원 등록 가능 상태 변경

src/main/java/com/spoonsors/spoonsorsserver/controller/member/BMemberController.java, src/main/java/com/spoonsors/spoonsorsserver/service/member/BMemberService.java
=> [#120]Feat: 수혜자 글 등록 가능 여부 확인api 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/review/ReviewController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/review/GetReviewDto.java, src/main/java/com/spoonsors/spoonsorsserver/service/review/ReviewService.java, src/main/java/com/spoonsors/spoonsorsserver/service/spon/SponService.java
=> [#130]Feat: 내가 받은 리뷰 확인 api 생성

src/main/java/com/spoonsors/spoonsorsserver/controller/payment/KakaoPayController.java, src/main/java/com/spoonsors/spoonsorsserver/entity/payment/PaymentDto.java, src/main/java/com/spoonsors/spoonsorsserver/repository/SponRepository.java, src/main/java/com/spoonsors/spoonsorsserver/service/payment/KakaoPayService.java, src/main/java/com/spoonsors/spoonsorsserver/service/spon/SponService.java
=> [#142]Fix: 결제 api 단건 결제->통합 결제로 변경
